#!/bin/sh
#/etc/init.d/install-picamera
### BEGIN INIT INFO
# Provides:          install-picamera
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Installs picamera legacy at first boot
# Description: On the first boot, this script will attempt to install the legacy picamera library. Hoping for the best, expecting the worst
### END INIT INFO
#!/bin/bash

python3 -m pip install /home/pi/picamera-1.13-py3-none-any.whl

sudo rm -f /home/pi/picamera-1.13-py3-none-any.whl

sudo rm -f /etc/init.d/install-picamera
